"use client";
import { useState } from "react";
import { ArrowUpRight, ArrowRight, Search, Plus, MoveUpRight } from "lucide-react";
import Link from "@/components/ui/NavigationLink";
import type { PublicIdea } from "@/lib/public-catalog";

export function Author({ idea }: { idea: PublicIdea }) {
  const content = <><span className="journal-avatar">{idea.authorName.slice(0, 1).toUpperCase()}</span><span>{idea.authorName}<small>分享了一个想法</small></span></>;
  return idea.authorId ? <Link className="journal-author" href={`/explore/people/${encodeURIComponent(idea.authorId)}`}>{content}</Link> : <div className="journal-author">{content}</div>;
}
export function IdeaJournal({ ideas, workspace = false }: { ideas: PublicIdea[]; workspace?: boolean }) {
  const [filter, setFilter] = useState("所有想法");
  const [query, setQuery] = useState("");
  const featured = ideas.filter(i => i.status !== "deprecated").sort((a,b) => Number(Boolean(b.problem)) - Number(Boolean(a.problem)) || b.works.length - a.works.length)[0];
  const visible = ideas.filter(i => `${i.title} ${i.summary} ${i.problem} ${i.authorName} ${i.tags.join(" ")}`.toLowerCase().includes(query.trim().toLowerCase()) && (filter === "所有想法" || filter === "已弃用" && i.status === "deprecated" || filter === "待人实现" && i.status !== "deprecated" && i.attemptCount === 0 || filter === "已经有人动手" && i.status !== "deprecated" && i.attemptCount > 0 || filter === "有了作品" && i.works.length > 0));
  return <div className="journal">
    <header className="journal-masthead"><span>THE OPEN NOTEBOOK</span><span>想法因分享而发生</span></header>
    <section className="journal-intro"><div><p className="journal-kicker">一个念头，也可以成为共同的起点。</p><h1>你在想什么<span>？</span><br />说出来，一起做。</h1></div><div className="journal-intro-aside"><p>那些生活里的「要是能……就好了」，<br />值得被更多人听见。<br />分享你的问题，遇见不同的解法。</p><Link href={workspace ? "/ideas/new" : "/register"}>写下我的想法 <Plus size={17} /></Link></div></section>
    {featured ? <section className="journal-feature"><div className="journal-feature-story"><div className="journal-feature-label"><span className="journal-dot" /> 从一个真实的问题开始 <span>01 / OPEN IDEA</span></div><Link href={`/explore/${featured.id}`}><h2>{featured.title}</h2><p className="journal-feature-quote">{featured.problem || featured.summary}</p></Link><div className="journal-feature-bottom"><Author idea={featured} /><Link className="journal-text-link" href={`/explore/${featured.id}`}>走进这个想法 <ArrowUpRight size={18}/></Link></div></div><div className="journal-feature-note"><span className="journal-note-pin"/><span className="journal-kicker">希望发生的改变</span><p>{featured.whyItMatters && featured.whyItMatters.trim() !== featured.problem.trim() ? featured.whyItMatters : featured.summary}</p><div><span>一个人的想法</span><ArrowRight size={18}/><span>更多人的可能</span></div><MoveUpRight className="journal-note-arrow" size={68} strokeWidth={1}/></div></section> : null}
    <section id="ideas" className="journal-catalog"><div className="journal-section-title"><div><span className="journal-kicker">IDEAS IN THE OPEN</span><h2>发现你也在意的事<span> / {ideas.length}</span></h2></div><label className="journal-search"><Search size={16}/><input aria-label="搜索想法" placeholder="一个问题、一个关键词…" value={query} onChange={e=>setQuery(e.target.value)}/>{query && <button aria-label="清除搜索" onClick={()=>setQuery("")}>×</button>}</label></div><div className="journal-filters">{["所有想法","待人实现","已经有人动手","有了作品","已弃用"].map(item=><button key={item} aria-pressed={filter===item} onClick={()=>setFilter(item)}>{item}</button>)}</div><p className="sr-only" role="status">找到 {visible.length} 个想法</p><div className="journal-grid">{visible.map((idea,index)=><article className={`journal-card ${idea.status === "deprecated" ? "is-deprecated" : ""}`} key={idea.id}><div className="journal-card-top"><span>{String(index+1).padStart(2,"0")}</span><span>{idea.tags[0] || "日常灵感"}</span>{idea.status === "deprecated" && <span className="idea-deprecated-badge">已弃用</span>}<ArrowUpRight size={18}/></div><Link className="journal-card-story" href={`/explore/${idea.id}`}><h3>{idea.title}</h3><p>{idea.problem || idea.summary}</p>{idea.whyItMatters && idea.whyItMatters.trim() !== (idea.problem || idea.summary).trim() && <div className="journal-card-wish">{idea.whyItMatters}</div>}</Link><div className="journal-card-bottom"><Author idea={idea}/><span className="journal-participation">{idea.status === "deprecated" ? "停止推进 · 保留记录" : idea.works.length ? `${idea.works.length} 个作品` : idea.attemptCount ? `${idea.attemptCount} 人在探索` : "等待第一个同行者"}</span></div></article>)}<article className="journal-invite"><span className="journal-invite-symbol">＋</span><h3>你的「要是能……」，<br/>也许有人正想做。</h3><p>不必有完整方案。一个真实的问题，<br/>就是很好的开始。</p><Link href={workspace ? "/ideas/new" : "/register"}>分享一个想法 <ArrowUpRight size={18}/></Link></article></div>{!visible.length && <div className="journal-empty"><p>这里还没有匹配的想法。换个关键词试试？</p><button onClick={()=>{setFilter("所有想法");setQuery("");}}>查看全部想法</button></div>}</section>
    <section id="how-it-works" className="journal-how"><div><span className="journal-kicker">GOOD IDEAS ARE BETTER SHARED</span><h2>从「我有一个想法」<br/>到「我们做出来了」。</h2></div>{[{n:"01",title:"说出你在意的",text:"从自己的经历出发，分享一个问题和你期待的改变。"},{n:"02",title:"带来你的解法",text:"找到有共鸣的想法，选择自己的方向，动手试一试。"},{n:"03",title:"把成果带回来",text:"让每份实现关联最初的想法，让每位贡献者被看见。"}].map(x=><div key={x.n}><span className="journal-kicker">{x.n}</span><h3>{x.title}</h3><p>{x.text}</p></div>)}</section>
  </div>;
}
